export default {
    CREATE_USER: 'CREATE_USER',
    LOAD_USER: 'LOAD_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOAD_DETAIL_USER: 'LOAD_DETAIL_USER',
    LOAD_USERS: 'LOAD_USERS',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    FILTERLIST: 'FILTERLIST'
};